### ISSUE TITLE
How to compile on x86 ?

### ISSUE THREAD

**Issue by TiBeN** [MarScaper/ephemeris#3]
Hi, 
I want to take a look at your library but, as a non C++ developper, i'm a little lost to compile it without makefile or build shell script.

Can you provide me a build command line for Linux ? 

Thanks

**Comment by TiBeN** [comment]
Not sure its the best way but i succeed with theses command lines:

```
g++ -c -fPIC Calendar.cpp -o Calendar.o
g++ -c -fPIC Ephemeris.cpp -o Ephemeris.o
g++ -shared Calendar.o Ephemeris.o -o Ephemeris.so
```

**Comment by 0xStarcat** [comment]
worked for me on g++ 6.3.0 however needed to include ` #include <stdint.h>` in `ELP2000.hpp` to resolve the error `‘int8_t’ does not name a type`
